### PR TITLE
Add src folder to npm

### PR DESCRIPTION
**Pull request by sifex**
So I was having a _real_ trouble finding methods in PHPStorm's autocomplete. Adding the src folder helped with this, 

screen shot 2018-12-19 at 9 09 36 am

screen shot 2018-12-19 at 8 59 14 am

### CODE REVIEW

**Comment by sifex** [comment]
The only problem I see is that now people have access to the src, they'll want to do stuff like:

```js
import Request from 'vue-mc/src/HTTP/Request'
import Response from 'vue-mc/src/HTTP/Response'
```

Which will 100% break if they're working on an ES6 project.

**Comment by rtheunissen** [comment]
> Which will 100% break if they're working on an ES6 project (which most are).

Why is this?

**Comment by rtheunissen** [comment]
We really need to bring some TS into this library..

**Comment by sifex** [comment]
@rtheunissen My mistake, it does compile fine when hard linked `ln` to the src folder

**Pull request closed without merging**
