### PR TITLE
Base params

### PR DESCRIPTION
**Pull request by throrin19**
I edit the `delete()` `save()` and `fetch()` functions to override and add specifics query params and/or headers : 

```js
this.collection.page(1).fetch({
    params : {
        param1 : "test",
        // ...
    }
});
```

### CODE REVIEW

**Comment by throrin19** [comment]
That's weird, When I launch the tests in my computer, I've no problem. But Travis crash on moxios part : 

```
moxios.requests.mostRecent().respondWith({
    status: 200,
    response: [],
});
```

**Comment by rtheunissen** [comment]
That does happen sometimes - it has to do with the mocking and "waiting" for requests. I've restarted the build so we should see it pass soon.

**Comment by rtheunissen** [comment]
Thank you so much for these changes @throrin19 :sparkles:

**Comment by throrin19** [comment]
Thanks for your merge. The new version will be published soon ?

**Comment by rtheunissen** [comment]
Yeah I think this is grounds for a 0.4, I'll package and release that asap.

**Comment by rtheunissen** [comment]
Released as 0.4.0

**Pull request merged**
