### PR TITLE
Convert to Typescript

### LINKED ISSUE #48: TypeScript support
Do you plan to add TypeScript definition file?

### PR DESCRIPTION
**Pull request by BehindTheMath**
Closes #48.

This is not ready to be merged yet, but I opened it to track the progress.

### CODE REVIEW

**Comment by BehindTheMath** [comment]
Rebased on master.

**Comment by BehindTheMath** [comment]
Rollup and Mocha seem to be working. nyc is not yet.

I'm not sure why there is a conflict. I rebased on master.

**Comment by xorik** [comment]
@BehindTheMath there are 3 news commits in master:
https://i.imgur.com/5eIcplW.png

**Comment by xorik** [comment]
Also why did you convert all the code to TS? I think it's much better to provide `d.ts` files, like vue does, with interfaces and methods

**Comment by BehindTheMath** [comment]
>@BehindTheMath there are 3 new commits in master:
>https://i.imgur.com/5eIcplW.png
>https://github.com/FiguredLimited/vue-mc/network

Good point.

>Also why did you convert all the code to TS? I think it's much better to provide d.ts files, like vue does, with interfaces and methods

That's what was requested [here](https://github.com/FiguredLimited/vue-mc/issues/48#issuecomment-431098941).

Vue itself is being converted to Typescript ([source](https://medium.com/the-vue-point/plans-for-the-next-iteration-of-vue-js-777ffea6fabf)).

**Comment by BehindTheMath** [comment]
The failed test is due to issue #132.

**Comment by BehindTheMath** [comment]
@rtheunissen This is ready to be reviewed and merged. Should I squash the commits?

**Comment by rtheunissen** [comment]
@BehindTheMath there is a conflict with locale.js that just came about. If you can resolve that I'm happy to merge this as is. No stress about squashing commits, your call. Thank you for your help on this.

**Comment by BehindTheMath** [comment]
@rtheunissen I rebased and squashed.

**Comment by rtheunissen** [comment]
🎉 Thanks for all the work you put into this @BehindTheMath

**Pull request merged**
