### PR TITLE
Save events (except save.always)

### PR DESCRIPTION
**Pull request by sergiuwd**

### CODE REVIEW

**Comment by rtheunissen** [comment]
We would need to update the tests accordingly also.

**Comment by sergiuwd** [comment]
@rtheunissen yea I noticed the tests are not working properly, as I said I don't have it installed as a package as I'm not using the code through yarn. I'll try to find some time tomorrow and update the tests.

**Comment by rtheunissen** [comment]
> I don't have it installed as a package as I'm not using the code through yarn

How else?

>  I'll try to find some time tomorrow and update the tests

I'll see if I can get around to this today, will update here.

**Comment by sergiuwd** [comment]
I just copied the src into my project as I’m making multiple customizations to the original files. Also, time is an issue as I only have 2-3 hours daily to work on the project that’s using vue-mc

**Comment by sergiuwd** [comment]
@rtheunissen updated the tests

**Pull request merged**
